[package]
name = "winbindings"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.17.1"

[build-dependencies]
windows = "0.17.1"
