name: Windows CI

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        build: [win32, win64]
        include:
        - build: win32
          os: windows-latest
          host_target: i686-pc-windows-msvc
        - build: win64
          os: windows-latest
          host_target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
        
    - run: rustup update --no-self-update && rustup +nightly target add ${{ matrix.host_target }}

    - name: build
      run: cargo +nightly build --target=${{ matrix.host_target }} --release

    - name: Upload dinput8.dll
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: dinput8-${{ matrix.host_target }}
        # A file, directory or wildcard pattern that describes what to upload
        path: target/${{ matrix.host_target }}/release/dinput8.dll